/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UdMnam06nkf
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Boss2() {
  return (
    <div
      key="1"
      className="flex flex-col h-screen w-full border-t-2 border-gray-100 dark:border-gray-800"
    >
      <div className="flex-1 border-b-2 border-gray-100 dark:border-gray-800">
        <div className="flex h-[60vh] items-stretch">
          <div className="hidden md:flex w-[400px] border-r-2 border-gray-100 dark:border-gray-800">
            <div className="flex flex-col h-screen w-full border-t-2 border-gray-100 dark:border-gray-800">
              <div className="flex-1 border-b-2 border-gray-100 dark:border-gray-800">
                <div className="flex h-[30vh] items-stretch">
                  <div className="hidden md:flex w-[400px] border-r-2 border-gray-100 dark:border-gray-800">
                    <div className="grid w-full grid-rows-[1fr]">
                      <div className="flex h-12 items-center p-4 border-b-2 border-gray-100 dark:border-gray-800" />
                      <div className="flex items-center justify-center p-4">
                        <Avatar className="w-32 h-32 border rounded-none">
                          <AvatarImage
                            alt="Support Agent"
                            // src="../../public/atlas.jpg"
                            src="atlas.jpg"
                          />
                          <AvatarFallback>SA</AvatarFallback>
                        </Avatar>
                      </div>
                      <div className="text-center text-sm mt-2">
                        Support Agent
                      </div>
                    </div>
                  </div>
                  <div className="flex-1 flex flex-col" />
                </div>
              </div>
            </div>
          </div>
          <div className="flex-1 flex flex-col">
            <div className="grid h-[100%] items-end p-4 gap-4">
              <div className="flex items-center justify-end rounded-xl bg-gray-100 p-4 dark:bg-gray-800">
                <div className="grid gap-1 text-sm">
                  <p>
                    Hi! 👋 I'm here to help with any questions you have about
                    our products or services.
                  </p>
                  <p>
                    Feel free to ask, and I'll do my best to provide you with
                    the information you need.
                  </p>
                </div>
              </div>
              <div className="flex items-center rounded-xl bg-gray-100 p-4 dark:bg-gray-800">
                <div className="grid gap-1 text-sm">
                  <p>
                    Hi! 👋 I'm here to help with any questions you have about
                    our products or services.
                  </p>
                  <p>
                    Feel free to ask, and I'll do my best to provide you with
                    the information you need.
                  </p>
                </div>
              </div>
              <div className="flex items-center rounded-xl bg-gray-100 p-4 dark:bg-gray-800">
                <div className="grid gap-1 text-sm">
                  <p>
                    Hi! 👋 I'm here to help with any questions you have about
                    our products or services.
                  </p>
                  <p>
                    Feel free to ask, and I'll do my best to provide you with
                    the information you need.
                  </p>
                </div>
              </div>
              <div>
                <form className="flex w-full gap-2">
                  <Input
                    className="flex-1 min-h-[40px]"
                    placeholder="Type a message..."
                  />
                  <Button type="submit">Send</Button>
                  <Button
                    className="bg-gray-100 dark:bg-gray-800"
                    type="button"
                  >
                    🎤
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
