/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UdMnam06nkf
 */
"use client";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { MicrophoneInput } from "../ui/MicrophoneInput";
import { MessageInput } from "../ui/MessageInput";
import { ChatArea } from "../ui/ChatArea";
import Navbar from "@/app/components/Navbar";
import { useEffect, useState } from "react";
import MobileAdvisorBanner from "../ui/MobileAdvisorBanner";

export function Boss({ persona }) {
  const [processedText, setProcessedText] = useState("");
  const [refinedText, setRefinedText] = useState("");
  const [submittedText, setSubmittedText] = useState("");
  const [filename, setFilename] = useState("");

  useEffect(() => {
    if (refinedText) {
      console.log("useEffect triggered for refinedText:", refinedText); // Debugging line
      // Assume you have an endpoint /generate-audio that accepts POST requests
      // and returns a URL to the generated audio file.
      fetch("http://localhost:5000/generate-audio", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          persona: persona,
        },
        body: JSON.stringify({ text: refinedText }),
      })
        .then((response) => response.json())
        .then((data) => {
          const audio = new Audio(data.audioUrl); // Assuming data.audioUrl is the URL to the audio file
          audio.play();
        })
        .catch((error) => console.error("Error:", error));
    }
  }, [refinedText]); // This effect depends on `refinedText`

  useEffect(() => {
    generateFilename(persona);
  }, [persona]);

  const generateFilename = () => {
    const now = new Date();
    const timestamp = `${now.getFullYear()}${padZero(
      now.getMonth() + 1
    )}${padZero(now.getDate())}_${padZero(now.getHours())}${padZero(
      now.getMinutes()
    )}${padZero(now.getSeconds())}`;
    // const persona = "trump";
    // const { persona } = props;
    const type = "log";
    const generatedFilename = `${persona}_${timestamp}_${type}.md`;
    setFilename(generatedFilename);
    console.log(generatedFilename);
  };

  const padZero = (num) => {
    return num.toString().padStart(2, "0");
  };

  const handleProcessedText = (text) => {
    console.log("Updating processed text with:", text);
    setProcessedText(text);
  };

  // This function is called by child components to update refined text
  const handleRefinedText = (text) => {
    console.log("Updating refined text with:", text);
    setRefinedText(text);
  };

  const handleFormSubmit = (textInput) => {
    console.log("Form submitted with text:", textInput);
    setSubmittedText(textInput); // Update the state with the submitted text
  };

  // useTextToSpeech(refinedText);

  return (
    <div className="flex flex-col h-screen">
      <Navbar />
      <MobileAdvisorBanner persona={persona} />
      <div key="1" className="flex flex-col flex-1">
        <div className="flex-1 overflow-y-auto">
          <ChatArea
            processedText={processedText}
            refinedText={refinedText}
            submittedText={submittedText} // Pass the submitted text as a prop
          />
        </div>
        <div className="p-4 flex gap-2 items-center">
          <MessageInput
            onProcessedText={handleProcessedText}
            onRefinedText={handleRefinedText}
            persona={persona}
            filename={filename}
            onFormSubmit={handleFormSubmit} // Pass the function as a prop
          />
          <MicrophoneInput
            onProcessedText={handleProcessedText}
            onRefinedText={handleRefinedText}
            persona={persona}
            filename={filename}
            onFormSubmit={handleFormSubmit} // Pass the function as a prop
          />
        </div>
      </div>
    </div>
  );
}
